name: RealmOfArcana
version: 0.1.1
author: Talvysh
main: com.realmofarcana.ROA
api-version: 1.18

commands:
  crowns:
    description: /? crowns
  rank:
    description: ranks
    usage: /rank
    permission: roa.ranks
  culling:
    description: Start/End The Culling
    usage: /culling
    permission: roa.culling
  uenchant:
    description: Unsafe enchantments
    usage: /uenchant
    permission: roa.uenchant
  gate:
    description: Gate commands
    usage: /gate
    permission: roa.gate
  region:
    usage: /region
    permission: roa.region
  land:
    usage: /land
    permission: roa.land
  bypass:
    usage: /bypass
    permission: roa.bypass
  "?":
    usage: /?
  member:
    description: member
    usage: /member
    permission: roa.member